=== baywind/XML-interchange-format/agregate.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT request (param*,grouping+)>
<!ATTLIST request
	entity CDATA #REQUIRED>

<!ELEMENT response (param*,grouping+)>
<!ATTLIST response
	entity CDATA #REQUIRED>

	
<!ELEMENT param (#PCDATA)>
<!ATTLIST param
	attribute CDATA #REQUIRED>
	
<!ELEMENT grouping (attribute+,agregate+)>
<!ATTLIST grouping
	stage CDATA #IMPLIED>

<!ELEMENT attribute (#PCDATA)>
<!ATTLIST attribute
	name CDATA #REQUIRED>

<!ELEMENT agregate (#PCDATA)>
<!ATTLIST agregate
	name CDATA #REQUIRED
	type (count|sum|avg) #IMPLIED
	attribute CDATA #IMPLIED>

=== baywind/XML-interchange-format/agrRequest.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ejdata PUBLIC "-//RUJEL//DTD ejif//RU" "./agregate.dtd">

<request entity = "itogMark">
	<param attribute = "eduYear">$eduYear</param>
	<param attribute = "perNum">$perNum</param>
	<param attribute = "perCount">$perCount</param>
	<grouping stage = "1">
		<attribute name="grade"/>
		<attribute name="student"/>
		<agregate name = "c0" type = "count">value=0</agregate>
		<agregate name = "c2" type = "count">value:(0,0.5)</agregate>
		<agregate name = "c3" type = "count">value:[0.5,0.7)</agregate>
		<agregate name = "c4" type = "count">value:[0.7,0.9)</agregate>
		<agregate name = "c5" type = "count">value>=0.9</agregate>
		<agregate name = "cn" type = "count">value=null</agregate>
	</grouping>
	<grouping stage="2">
		<attribute name="grade"/>
		<agregate name="total" type="count"/>
		<agregate name="fine" type="count">c0=0&amp;c2=0</agregate>
		<agregate name="exl" type="count">c0=0&amp;c2=0&amp;c3=0&amp;c4=0</agregate>
		<agregate name="good" type="count">c0=0&amp;c2=0&amp;c3=0</agregate>
		<agregate name="one4" type="count">c0=0&amp;c2=0&amp;c3=0&amp;c4=1</agregate>
		<agregate name="one3" type="count">c0=0&amp;c2=0&amp;c3=1</agregate>
		<agregate name="na" type="count">c0>0</agregate>
		<agregate name="bad" type="count">c0=0&amp;c2>0</agregate>
		<agregate name="bad1" type="count">c0=0&amp;c2=1</agregate>
		<agregate name="bad2" type="count">c0=0&amp;c2=2</agregate>
		<agregate name="worse" type="count">c0=0&amp;c2>2</agregate>
		<agregate name="cnSum" type="sum" attribute ="cn"/>
	</grouping>
</request>

=== baywind/XML-interchange-format/agrResponse.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE request SYSTEM "agregate.dtd" >
<response entity="itogMark">
	<param attribute = "eduYear">2011</param>
	<param attribute = "perNum">1</param>
	<param attribute = "perCount">1</param>
	<grouping stage="2">
		<attribute name="grade">5</attribute>
		<agregate name="total" type="count">37</agregate>
		<agregate name="fine" type="count">32</agregate>
		<agregate name="exl" type="count">1</agregate>
		<agregate name="good" type="count">12</agregate>
		<agregate name="one4" type="count">0</agregate>
		<agregate name="one3" type="count">3</agregate>
		<agregate name="na" type="count">4</agregate>
		<agregate name="bad" type="count">1</agregate>
		<agregate name="bad1" type="count">1</agregate>
		<agregate name="bad2" type="count">0</agregate>
		<agregate name="worse" type="count">0</agregate>
		<agregate name="cnSum" type="sum" attribute ="cn">2</agregate>
	</grouping>
	<grouping stage="2">
		<attribute name="grade">6</attribute>
		<agregate name="total" type="count">42</agregate>
		<agregate name="fine" type="count">36</agregate>
		<agregate name="exl" type="count">0</agregate>
		<agregate name="good" type="count">13</agregate>
		<agregate name="one4" type="count">0</agregate>
		<agregate name="one3" type="count">3</agregate>
		<agregate name="na" type="count">6</agregate>
		<agregate name="bad" type="count">0</agregate>
		<agregate name="bad1" type="count">0</agregate>
		<agregate name="bad2" type="count">0</agregate>
		<agregate name="worse" type="count">0</agregate>
		<agregate name="cnSum" type="sum" attribute ="cn">0</agregate>
	</grouping>
	<grouping stage="2">
		<attribute name="grade">7</attribute>
		<agregate name="total" type="count">57</agregate>
		<agregate name="fine" type="count">43</agregate>
		<agregate name="exl" type="count">0</agregate>
		<agregate name="good" type="count">12</agregate>
		<agregate name="one4" type="count">1</agregate>
		<agregate name="one3" type="count">4</agregate>
		<agregate name="na" type="count">6</agregate>
		<agregate name="bad" type="count">8</agregate>
		<agregate name="bad1" type="count">4</agregate>
		<agregate name="bad2" type="count">2</agregate>
		<agregate name="worse" type="count">2</agregate>
		<agregate name="cnSum" type="sum" attribute ="cn">30</agregate>
	</grouping>
	<grouping stage="2">
		<attribute name="grade">8</attribute>
		<agregate name="total" type="count">30</agregate>
		<agregate name="fine" type="count">20</agregate>
		<agregate name="exl" type="count">0</agregate>
		<agregate name="good" type="count">7</agregate>
		<agregate name="one4" type="count">1</agregate>
		<agregate name="one3" type="count">1</agregate>
		<agregate name="na" type="count">7</agregate>
		<agregate name="bad" type="count">3</agregate>
		<agregate name="bad1" type="count">1</agregate>
		<agregate name="bad2" type="count">0</agregate>
		<agregate name="worse" type="count">2</agregate>
		<agregate name="cnSum" type="sum" attribute ="cn">2</agregate>
	</grouping>
	<grouping stage="2">
		<attribute name="grade">9</attribute>
		<agregate name="total" type="count">48</agregate>
		<agregate name="fine" type="count">31</agregate>
		<agregate name="exl" type="count">0</agregate>
		<agregate name="good" type="count">5</agregate>
		<agregate name="one4" type="count">0</agregate>
		<agregate name="one3" type="count">1</agregate>
		<agregate name="na" type="count">4</agregate>
		<agregate name="bad" type="count">13</agregate>
		<agregate name="bad1" type="count">4</agregate>
		<agregate name="bad2" type="count">2</agregate>
		<agregate name="worse" type="count">8</agregate>
		<agregate name="cnSum" type="sum" attribute ="cn">0</agregate>
	</grouping>
</response>
