=== baywind/XML-interchange-format/ejdata.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT ejdata (eduGroups?, teachers, courses)>
<!-- в заголовке представлен источник. атрибуты:
	product - название программного средства - источника данного файла.
			должен быть неизменным для всех версий данного ПО, чтобы другие программы могли
			при импорте использовать платформозависимые данные 
	version - номер версии ПО - источника
	base - содержит произвольную строку, позволяющую точно идентифицировать источник данных
	eduYear - учебный год, для которого актуальны эти данные
			год в 4-значном формате только первый (т.е. 2010/11 записывается как 2010) -->
<!ATTLIST ejdata 
	product CDATA #REQUIRED
	version CDATA #IMPLIED
	base CDATA #REQUIRED
	eduYear CDATA #REQUIRED>

<!ELEMENT eduGroups (eduGroup+)>

<!ELEMENT eduGroup (syncdata?, person*)>
<!-- учебная группа (класс).
	name - полное название (5 А)
	grade - только цифра класса
	title - только буква класса (или другое отличительное наименование в одном grade)
	absGade - значение /eduYear - grade/ 
			актуально, если на каждый учебный год не создается новый объек т(запись) класса -->
<!ATTLIST eduGroup
	id CDATA #REQUIRED
	name CDATA #REQUIRED
	grade CDATA #IMPLIED
	absGrade CDATA #IMPLIED
	title CDATA #IMPLIED>

<!ELEMENT syncdata (extid+)>
<!-- данные для упрощения синхронизации различных информационных систем
	в элементах extid указываются известные идентификаторы данного объекта в разных ИС
	см. комментарий к ejdata -->

<!ELEMENT extid EMPTY>
<!ATTLIST extid
    base CDATA #REQUIRED
    id CDATA #REQUIRED
    product CDATA #REQUIRED>

<!ELEMENT person (syncdata?, name*, date?)>
<!ATTLIST person
	type (student|teacher|parent|other) #REQUIRED
    id CDATA #REQUIRED
    fullname CDATA #IMPLIED>

<!ELEMENT name (#PCDATA)>
<!ATTLIST name
    type (last|first|second|other) #REQUIRED>

<!ELEMENT date EMPTY>
<!ATTLIST date
    birth CDATA #REQUIRED
    death CDATA #IMPLIED>

<!ELEMENT teachers (person+)>

<!ELEMENT courses (course+)>

<!ELEMENT course (syncdata?, person*, comment?, cycle?, subgroup?, planning?, critSet?, containers*)>
<!ATTLIST course
    id CDATA #REQUIRED
    eduGroup CDATA #REQUIRED
    subject CDATA #REQUIRED>

<!ELEMENT comment (#PCDATA)>
<!ATTLIST comment type CDATA #IMPLIED>

<!ELEMENT cycle (syncdata?, subject, hours?)>
<!ATTLIST cycle
    grade CDATA #REQUIRED
    id CDATA #REQUIRED>

<!ELEMENT subject EMPTY>
<!ATTLIST subject
    id CDATA #REQUIRED
    fullname CDATA #IMPLIED
    title CDATA #REQUIRED>

<!ELEMENT hours EMPTY>
<!ATTLIST hours
    weekly CDATA #IMPLIED
    yearly CDATA #IMPLIED>

<!ELEMENT subgroup (person+)>
<!ATTLIST subgroup
    type (sub|full|mixed) #REQUIRED>

<!ELEMENT planning (syncdata?, person?, comment?, planTheme*, materials?)>
<!ATTLIST planning
    id CDATA #IMPLIED>

<!ELEMENT planTheme (syncdata?, content?, materials?)>
<!ATTLIST planTheme
    id CDATA #REQUIRED
    hours CDATA #IMPLIED
    num CDATA #IMPLIED>

<!ELEMENT content (#PCDATA)>

<!ELEMENT materials (book | media)+>

<!ELEMENT book (#PCDATA)>
<!ATTLIST book
    authors CDATA #IMPLIED
    publisher CDATA #IMPLIED
    type CDATA #IMPLIED>

<!ELEMENT media (#PCDATA)>
<!ATTLIST media
    mimeType CDATA #IMPLIED
    url CDATA #REQUIRED>

<!ELEMENT critSet (criterion+)>

<!ELEMENT criterion (comment?,indexer?)>
<!ATTLIST criterion
    idx CDATA #REQUIRED
    max CDATA #IMPLIED
    title CDATA #REQUIRED
    weight CDATA #IMPLIED>

<!ELEMENT indexer (media?,indexRow+)>
<!ATTLIST indexer
    id CDATA #REQUIRED
    type (text|color|image|media) #REQUIRED>

<!ELEMENT indexRow (comment)?>
<!ATTLIST indexRow
    present CDATA #REQUIRED
    value CDATA #REQUIRED>


<!ELEMENT containers (container+)>
<!ATTLIST containers
    type (lesson|work|itog|prognosis|other) #REQUIRED>

<!ELEMENT container (syncdata?,content?,planTheme?,task?,criteria?,calc?,param*,marks?)>
<!ATTLIST container
    id CDATA #REQUIRED
    announce CDATA #IMPLIED
    num CDATA #IMPLIED
    date CDATA #IMPLIED
    time CDATA #IMPLIED
    title CDATA #IMPLIED
    type CDATA #IMPLIED>

<!ELEMENT present (#PCDATA)>
<!ATTLIST present
    type (inner|text|color|image|media) #REQUIRED
    mimeType CDATA #IMPLIED>

<!ELEMENT task (#PCDATA)>

<!ELEMENT criteria (criterion)+>

<!ELEMENT calc EMPTY>
<!ATTLIST calc
	weight CDATA "1"
	compulsory (true|false) "false">

<!ELEMENT param (#PCDATA)>
<!ATTLIST param
    key CDATA #REQUIRED>

<!ELEMENT marks (mark)+>

<!ELEMENT mark (crmark*,comment?,present*,param*)>
<!ATTLIST mark
    student CDATA #REQUIRED
    value CDATA #IMPLIED>

<!ELEMENT crmark (present)?>
<!ATTLIST crmark
    criter CDATA #REQUIRED
    value CDATA #REQUIRED>

=== baywind/XML-interchange-format/interchange.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ejdata PUBLIC "-//RUJEL//DTD ejif//RU" "./ejdata.dtd">
<ejdata product="Rujel" base="rujel.ms45.edu.ru" eduYear="2010">
	<!-- в заголовке представлен источник
	атрибут base содержит произвольную строку, позволяющую точно идентифицировать источник данных
	логично использовать доменное имя, но это не принципиально -->
<school title = "Гимназия №45" fullname = "ГОУ Гимназия №45">
	<adres>г. Москва, ул. Гримау, д. 8</adres>
	<weblink>http://ms45.edu.ru</weblink>
</school>
<eduGroups>
	<eduGroup id="24" name="5 а" grade="5" title="а" absGrade="2005">
		<syncdata>
			<!-- модуль синхронизации может использовать вспомогательную таблицу БД,
				в которой будут храниться известные ему по предыдущим синхронизациям
				идентификаторы объектов в синхронизуемых базах.
				Это позволит упростить повторные синхронизации -->
			<extid product="Moodle" base="moodle.ms45.edu.ru" id="14" />
			<extid product="SocNet" base="net.socedu.ru" id="517" />
		</syncdata>
		<person type="student" id="317" fullname="Иванов В. П.">
			<syncdata>
				<extid product="Moodle" base="moodle.ms45.edu.ru" id="134" />
				<extid product="SocNet" base="net.socedu.ru" id="2178" />
			</syncdata>
			<name type="last">Иванов</name>
			<name type="first">Василий</name>
			<name type="second">Петрович</name>
			<date birth="2000-04-16" />
		</person>
		<person type="student" id="318" fullname="Васнецова Г. С.">
			<syncdata>
				<extid product="Moodle" base="moodle.ms45.edu.ru" id="135" />
				<extid product="SocNet" base="net.socedu.ru" id="2179" />
			</syncdata>
			<name type="last">Васнецова</name>
			<name type="first">Галина</name>
			<name type="second">Сергеевна</name>
			<date birth="2000-02-26" />
		</person>
		<person type="student" id="287" fullname="Шаталов В. Т.">
			<syncdata>
				<extid product="Moodle" base="moodle.ms45.edu.ru" id="121" />
			</syncdata>
			<name type="last">Шаталов</name>
			<name type="first">Владимир</name>
			<name type="second">Тарасович</name>
			<date birth="1998-08-21" />
		</person>
	</eduGroup>
</eduGroups>
<teachers>
	<person type="teacher" id="12" fullname="Сергеева М. И.">
			<syncdata>
				<extid product="Moodle" base="moodle.ms45.edu.ru" id="135" />
				<extid product="SocNet" base="net.socedu.ru" id="2179" />
			</syncdata>
			<name type="last">Сергеева</name>
			<name type="first">Мария</name>
			<name type="second">Ивановна</name>
			<date birth="1976-08-22" />
	</person>
</teachers>
<courses>
	<course id="37" subject="Математика" eduGroup="24">
		<syncdata>
			<extid product="Moodle" base="moodle.ms45.edu.ru" id="23" />
		</syncdata>
		<subject id="2" title="Математика">
			<content>Основы математической науки</content>
		</subject>
		<person type="teacher" id="12" fullname="Сергеева М. И." />
		<comment>экспериментальная программа</comment>
		<subgroup type = "sub">
			<!-- Для курсов, на которые ходит не весь класс или дети из разных классов,
				можно явно прописать список учащихся.
				имя указывать здесь необязательно, если учащиеся уже были описаны ранее. -->
			<person type="student" id="317" fullname="Иванов Василий" />
			<person type="student" id="318" fullname="Васнецова Галина" />
			<person type="student" id="287" fullname="Шаталов Владимир" />
		</subgroup>
		<planning id="6">
			<!-- тематическое планирование. Примитивный вариант.
				Пока сами не реализовали, более подробное описание напишу вряд ли -->
			<person type="teacher" id="12" />
			<comment>Экспериментальная разработка.
				Занятия проводятся в игровой форме. Изучаемый материал подается в видеозаписи.
			</comment>
			<planTheme id="1" hours="1">
				<content>Введение</content>
			</planTheme>
			<planTheme id="2" hours="4">
				<content>Доли и дроби</content>
				<materials>
				<!-- раздел материалов требует доработки. я не знаю, как описать ЦОРы -->
					<book type="доп. литература" authors="Шарыгин И. П." publisher="Питер">
						Деление на пальцах
					</book>
					<media url="http://math.edu.ru/primitive/fractions.html" mimeType="text/html">
						Занятные примеры на деление
					</media>
				</materials>
			</planTheme>
			<materials>
					<book type="учебник" authors="Автор Х. З." publisher="Просвещение">
						Математика 5
					</book>
			</materials>
		</planning>
		<!-- разные типы оценок по сути не различаются между собой.
			отличие состоит только в типе контейнера: урок/работа/прогноз/итоговая -->
		<critSet>
			<criterion idx="1" title="A" max="8" weight="4">
				<comment>Знание и понимание</comment>
			</criterion>
			<criterion idx="2" title="B" max="100" weight="2">
				<comment>Способность формулировать мысли</comment>
				<indexer id="1" type="text">
					<indexRow value="20" present="1"/>
					<indexRow value="35" present="2"/>
					<indexRow value="52" present="3"/>
					<indexRow value="74" present="4"/>
					<indexRow value="83" present="5"/>
					<indexRow value="100" present="6"/>
				</indexer>
			</criterion>
			<criterion idx="3" title="C" max="100" weight="1">
				<comment> Достижения в картинках</comment>
				<indexer id="2" type="image">
					<media url="http://ms45.edu.ru/crpics/" mimeType="image/gif" />
					<indexRow value="20" present="bad.gif">
						<comment>Может только повторить сказанное 10 минут назад</comment>
					</indexRow>
					<indexRow value="50" present="neutral.gif">
						<comment>
							В состоянии воспроизвести материал последней пройденной темы
						</comment>
					</indexRow>
					<indexRow value="70" present="fine.gif">
						<comment>
							Может объяснить пройденный материал своими словами и привести примеры
						</comment>
					</indexRow>
					<indexRow value="90" present="super.gif">
						<comment>
							может анализировать материал и делать на его основе выводы, 
							приводящие к следующей теме
						</comment>
					</indexRow>
				</indexer>
			</criterion>
		</critSet>
		<!-- все отметки друг от друга практически не отличаются по сути.
			разные типы отметок помещаем в разные блоки контейнеров 
			по типам "урок", "работа", "итоговая" -->
		<containers type="lesson">
			<container id="719" date="2010-09-03">
				<content>Вводное занятие. Техника безопасности.</content>
				<planTheme id="1"/>
				<task>Повторить таблицу умножения</task>
				<marks>
					<mark student="287" value="Н" />
					<mark student="317">
						<comment>Плевался в соседа по парте</comment>
					</mark>
					<!-- Хотя, по сути, отличия нет, но возможно длинные замечания логично
						помещать в отдельный блок, а краткие отметки записывать параметром.
						В каких-то системах логика хранения отметок и замечаний может отличаться.
						например, отметка Н может сохраняться в подсистеме посещаемости -->
				</marks>
			</container>
			<container id="720" date="2010-09-10">
				<content>Простые дроби</content>
				<planTheme id="2" num="1"/>
				<task>см. в Moodle</task>
			</container>
		</containers>
		<containers type="work">
			<container id="634" num="1" date="2010-09-07" type="домашняя">
				<content>Повторить таблицу умножения</content>
				<task>http://math.edu.ru/primitive/multiplicationTable.html</task>
			</container>
			<container id="635" num="2" date="2010-09-07" type="классная">
				<content>Проверочная работа по таблице умножения</content>
				<criteria>
					<criterion idx="1" title="A" max="8" weight="4" />
					<criterion idx="3" title="C" max="100" weight="1" />
				</criteria>
				<calc compulsory = "true" weight = "0.5"/>
				<marks>
 					<mark student="287" value="2">
 						<crmark criter="1" value="3" />
 						<crmark criter="3" value="20">
 							<present type="image">bad.gif</present>
 						</crmark>
 						<comment>Списывал</comment>
 						<present type="inner">0.34</present>
 						<present type="color">#ff6666</present>
 					</mark>
					<mark student="317" value="3">
 						<crmark criter="1" value="5" />
 						<crmark criter="3" value="70">
 							<present type="image">fine.gif</present>
 						</crmark>
 						<present type="inner">0.64</present>
 						<present type="color">#ffff33</present>
					</mark>
					<mark student="318" value="5">
 						<crmark criter="1" value="8" />
 						<crmark criter="3" value="100">
 							<present type="image">super.gif</present>
 						</crmark>
 						<comment>Великолепная работа</comment>
 						<present type="inner">1.0</present>
 						<present type="color">#99ff66</present>
					</mark>
				</marks>
			</container>
			<container id="636" num="3" date="2010-09-08" type="домашняя">
				<syncdata>
					<extid product="Moodle" base="moodle.ms45.edu.ru" id="413" />
				</syncdata>
				<content>см. в Moodle</content>
				<task>http://moodle.ms45.edu.ru/task.php?id=413</task>
				<calc weight = "0.4"/>
				<!-- дополнительные параметры характерые для конкретного ПО -->
				<param key = "hometask">true</param>
				<param key = "announce">2010-09-07</param>
				<param key = "load">30</param>
			</container>
		</containers>
		<containers type="prognosis">
			<container id="9" date="2010-10-29" num = "1" type="триместр" title="I трм">
				<content>I триместр</content>
				<param key="flags">5</param>
				<param key = "time">23:55:00</param>
				<marks>
					<mark student="287" value="н/а">
						<present type="inner">0.0</present>
						<param key="complete">0.0</param>
						<param key="flags">3</param>
					</mark>
					<mark student="317" value="4">
						<present type="inner">0.7684</present>
						<param key="complete">1.0</param>
						<param key="flags">4</param>
					</mark>
					<mark student="318" value="5">
						<present type="inner">1.0</present>
						<param key="complete">1.0</param>
						<param key="flags">9</param>
					</mark>
				</marks>
			</container>
		</containers>
		<containers type="itog">
			<container id="9" num="1" type="триместр" title="I трм">
				<syncdata>
					<extid product="Moodle" base="moodle.ms45.edu.ru" id="3" />
				</syncdata>
				<content>I триместр</content>
				<marks>
					<mark student="287" value="н/а">
