=== baywind/XML-interchange-format/persdata.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT persdata (person+)>
<!ATTLIST persdata 
	product CDATA #REQUIRED
	version CDATA #IMPLIED
	base CDATA #REQUIRED
	eduYear CDATA #REQUIRED>

<!ELEMENT syncdata (extid+)>

<!ELEMENT extid EMPTY>
<!ATTLIST extid
    base CDATA #REQUIRED
    product CDATA #REQUIRED
    entity CDATA #IMPLIED
    id CDATA #REQUIRED>

<!ELEMENT person (syncdata?, name*, date?)>
<!ATTLIST person
	type (student|teacher|parent|other) #REQUIRED
    id CDATA #REQUIRED
    sex (male|female) #REQUIRED>

<!ELEMENT name (#PCDATA)>
<!ATTLIST name
    type (last|first|second|other) #REQUIRED>

<!ELEMENT date EMPTY>
<!ATTLIST date
    birth CDATA #REQUIRED
    death CDATA #IMPLIED>

=== baywind/XML-interchange-format/persons.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE persdata SYSTEM "persdata.dtd" >
<persdata product="Rujel" base="rujel.ms45.edu.ru" eduYear="2010">
	<person type="student" id="317" sex = "male" absGrade="2005">
		<syncdata>
			<extid product="Moodle" base="moodle.ms45.edu.ru">134</extid>
			<extid product="SocNet" base="net.socedu.ru">2178</extid>
			<extid product="Rujel" base="rujel.ms45.edu.ru" entity = "Person">219</extid>
		</syncdata>
		<name type="last">Иванов</name>
		<name type="first">Василий</name>
		<name type="second">Петрович</name>
		<date type="birth">2000-04-16</date>
	</person>
	<person type="student" id="318" sex = "female" absGrade="2005">
		<syncdata>
			<extid product="Moodle" base="moodle.ms45.edu.ru">135</extid>
			<extid product="SocNet" base="net.socedu.ru">2179</extid>
			<extid product="Rujel" base="rujel.ms45.edu.ru" entity = "Person">220</extid>
		</syncdata>
		<name type="last">Васнецова</name>
		<name type="first">Галина</name>
		<name type="second">Сергеевна</name>
		<date type="birth">2000-02-26</date>
	</person>
	<person type="student" id="287" sex = "male" absGrade="2005">
		<syncdata>
			<extid product="Moodle" base="moodle.ms45.edu.ru">121</extid>
			<extid product="Rujel" base="rujel.ms45.edu.ru" entity = "Person">537</extid>
		</syncdata>
		<name type="last">Шаталов</name>
		<name type="first">Владимир</name>
		<name type="second">Тарасович</name>
		<date type="birth">1998-08-21</date>
	</person>
	<person type="teacher" id="12" sex = "female">
		<syncdata>
			<extid product="Moodle" base="moodle.ms45.edu.ru">135</extid>
			<extid product="SocNet" base="net.socedu.ru">2179</extid>
			<extid product="Rujel" base="rujel.ms45.edu.ru" entity = "Person">111</extid>
		</syncdata>
		<name type="last">Сергеева</name>
		<name type="first">Мария</name>
		<name type="second">Ивановна</name>
		<date type="birth">1976-08-22</date>
	</person>
</persdata>
